### ISSUE TITLE
System.InvalidOperationException : The binary operator GreaterThan is not defined for the types 'System.String' and 'System.String'.

### ISSUE THREAD

**Issue by aroravi** [willianantunes/drf-like-paginations#5]
I'm getting this message when passing defaultFieldForOrdering = "Name" in a CursorPagination constructor. Are there any work arounds, or fixes for this? Otherwise, your assembly is fantastic. Saved me hours of work.

BTW, I'm running unit test and passing "Name" as parameter for sorting. Please see the test method
```
[Fact(DisplayName = "When no options are provided ASC ORDERING")]
            public async Task ShouldCreatePaginatedScenarioOptions1()
            {
                // Arrange
                _pagination = new CursorPagination(_defaultPageLimit, _defaultMaxPageLimit, "Name");
                var query = await CreateScenarioWith50Situations(_dbContext);
                var queryParams = Http.RetrieveQueryCollectionFromQueryString("cursor=cj1GYWxzZSZwPVNpdHVhdGlvbisxNg%3d%3d&limit=10");
                // Act
                var paginated = await _pagination.CreateAsync(query, _url, queryParams);
                // Assert
                paginated.Count.Should().BeNull();
                paginated.Results.Should().HaveCount(_defaultPageLimit);
                paginated.Previous.Should().BeNull();
                var allRetrievedIds = paginated.Results.Select(v => v.Id).ToList();
                var expectedRetrievedIds = new List<int> { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
                allRetrievedIds.Should().Equal(expectedRetrievedIds);
                var paginatedNext = paginated.Next;
                paginatedNext.Should().StartWith("https://www.willianantunes.com/?");
                var paginationSetup = BuildPaginationSetup(paginated.Next)!;
                paginationSetup.Reverse.Should().BeFalse();
                int.Parse(paginationSetup.Position!).Should().Be(10);
                int.Parse(paginationSetup.Limit!).Should().Be(_defaultPageLimit);
            }
```
Please see the stack-trace info for your reference.
```
[xUnit.net 00:00:01.58]   Starting:    Tests
[xUnit.net 00:00:34.65]     When no options are provided ASC ORDERING [FAIL]
[xUnit.net 00:00:34.65]       System.InvalidOperationException : The binary operator GreaterThan is not defined for the types 'System.String' and 'System.String'.
[xUnit.net 00:00:34.66]       Stack Trace:
[xUnit.net 00:00:34.66]            at System.Linq.Expressions.Expression.GetUserDefinedBinaryOperatorOrThrow(ExpressionType binaryType, String name, Expression left, Expression right, Boolean liftToNull)
[xUnit.net 00:00:34.66]            at System.Linq.Expressions.Expression.GetComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
[xUnit.net 00:00:34.66]            at System.Linq.Expressions.Expression.GreaterThan(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
[xUnit.net 00:00:34.66]            at System.Linq.Expressions.Expression.GreaterThan(Expression left, Expression right)
[xUnit.net 00:00:34.66]         /Users/aroravi/Documents/Practice/drf-like-paginations/src/CursorPagination.cs(285,0): at DrfLikePaginations.CursorPagination.ApplyFilterIfRequired[T](IQueryable`1 source, CursorDetails cursor)
[xUnit.net 00:00:34.66]         /Users/aroravi/Documents/Practice/drf-like-paginations/src/CursorPagination.cs(57,0): at DrfLikePaginations.CursorPagination.CreateAsync[T](IQueryable`1 source, String url, IQueryCollection queryParams)
[xUnit.net 00:00:34.66]         /Users/aroravi/Documents/Practice/drf-like-paginations/tests/DrfLikePaginations/CursorPaginationITests.cs(44,0): at Tests.DrfLikePaginations.CursorPaginationITests.Options.ShouldCreatePaginatedScenarioOptions1()
[xUnit.net 00:00:34.66]         --- End of stack trace from previous location ---
[xUnit.net 00:00:34.67]   Finished:    Tests
Debugging complete. 
```

**Comment by willianantunes** [comment]
Hi @aroravi!

> I'm getting this message when passing defaultFieldForOrdering = "Name" in a CursorPagination constructor

It seems that this field might bring you trouble if you try to use as an ordering factor for `CursorPagination`. If you look at the section [Details and Limitations](https://www.django-rest-framework.org/api-guide/pagination/#details-and-limitations) of `CursorPagination` on DRF website, it states that the field configured to apply the ordering must satisfies the following:

- Should be an unchanging value, such as a timestamp, slug, or other field that is only set once, on creation.
- Should be unique, or nearly unique. Millisecond precision timestamps are a good example. This implementation of cursor pagination uses a smart "position plus offset" style that allows it to properly support not-strictly-unique values as the ordering.
- Should be a non-nullable value that can be coerced to a string.
- Should not be a float. Precision errors easily lead to incorrect results. Hint: use decimals instead. (If you already have a float field and must paginate on that, an example CursorPagination subclass that uses decimals to limit precision is available here.)
- The field should have a database index.

Apart from that, the code fragment where this logic is applied is [here](https://github.com/willianantunes/drf-like-paginations/blob/9bb542cfe361fd7710f7a46e21c44e62dc028aa2/src/CursorPagination.cs#L282-L287). I have no time to fix it this month or even the next one. If you know how to solve it, you can create a PR with the fix.
